### ISSUE TITLE
Adapting this add-in for Outlook

### ISSUE THREAD

**Issue by torres-pedro** [microsoftgraph/msgraph-training-office-addin#11]
I was trying to use this tutorial as a basis to create a similar add-in but for Outlook.
I think I all the required changes to make the addin compatible with Outlook, as I am able to install the add-on on Outlook via the manifesto. But the Office.OnReady() function doesn't seem to fire off and the message in the taskpane is just "Checking authorization...". What could be the issue here?

I used `npx office-addin-manifest validate manifest.xml ` to see if the manifesto is valid and got an error: `Error: Cannot find module 'fs-extra'`, although only `fs` is used, since I did not change any of the server/api files from the tutorial, only the manifesto and the taspane.ts to have Outlook instead of Excel.

Anny help is much appreciated!

**Comment by jasonjoh** [comment]
Hi @torres-pedro unfortunately we can't provide troubleshooting here in GitHub that's not directly related to the sample in this repo. It's been years since I've done anything with Outlook add-ins, but something to check might be if your Outlook supports dialog API.
